---
title: "Untitled"
output: html_document
runtime: shiny
---
```{r}
library(shiny)

ui <- fluidPage(
  sliderInput(inputId = "num", label = "choose a number", value = 25, min = 1, max = 100),
  textInput(inputId = "title",label = "write a title", value = ""),
  actionButton(inputId = "go", label = "update"),
  plotOutput("hist")
  
)

server <- function(input, output, session) {
   data <- eventReactive(input$go, {
    rnorm(input$num) 
  })
  
  output$hist <- renderPlot({
    hist(data(), main = input$title)
  })
}

shinyApp(ui, server)
```

#upload a file in shiny app
```{r}
library(shiny)

ui <- fluidPage(
  titlePanel("Uploading Files"),

  # Sidebar layout with input and output definitions ----
  sidebarLayout(

    # Sidebar panel for inputs ----
    sidebarPanel(

      # Input: Select a file ----
      fileInput("file1", "Choose CSV File",
                multiple = TRUE,
                accept = c("text/csv",
                         "text/comma-separated-values,text/plain",
                         ".csv")),

      # Horizontal line ----
      tags$hr(),

      # Input: Checkbox if file has header ----
      checkboxInput("header", "Header", TRUE),

      # Input: Select separator ----
      radioButtons("sep", "Separator",
                   choices = c(Comma = ",",
                               Semicolon = ";",
                               Tab = "\t"),
                   selected = ","),

      # Input: Select quotes ----
      radioButtons("quote", "Quote",
                   choices = c(None = "",
                               "Double Quote" = '"',
                               "Single Quote" = "'"),
                   selected = '"'),

      # Horizontal line ----
      tags$hr(),

      # Input: Select number of rows to display ----
      radioButtons("disp", "Display",
                   choices = c(Head = "head",
                               All = "all"),
                   selected = "head")

    ),

    # Main panel for displaying outputs ----
    mainPanel(

      # Output: Data file ----
      tableOutput("contents")

    )

  )
)

server <- function(input, output) {

  output$contents <- renderTable({

    # input$file1 will be NULL initially. After the user selects
    # and uploads a file, head of that data file by default,
    # or all rows if selected, will be shown.

    req(input$file1)

    df <- read.csv(input$file1$datapath,
             header = input$header,
             sep = input$sep,
             quote = input$quote)

    if(input$disp == "head") {
      return(head(df))
    }
    else {
      return(df)
    }

  })

}

shinyApp(ui, server)
```

```{r}
demographic = read.csv("~/Project_Manny/Shiny/demographic.csv")
head(demographic)
```


```{r}
library(RSQLite)
drv<-dbDriver("SQLite")
con<-dbConnect(drv, "NewDemographic.sqlite")
```


```{r}
if (dbExistsTable(con, "demographic")) {
  dbSendQuery(con, "drop table demographic")
}

```

```{r}
dbWriteTable(con, "demographic", demographic)

```

```{r}
dbGetQuery(con, "SELECT * from demographic limit 10")

```

```{r}
dbGetQuery(con, "PRAGMA table_info(demographic)")

```

```{r}
genelist = read.delim("~/Project_Manny/Shiny/test/genelist.txt",header = TRUE, comment.char="#")
head(genelist)
```


```{r}
library(RSQLite)
drv<-dbDriver("SQLite")
con<-dbConnect(drv, "genelist.sqlite")
```


```{r}
if (dbExistsTable(con, "genelist")) {
  dbSendQuery(con, "drop table genelist")
}

```

```{r}
dbWriteTable(con, "genelist", genelist)

```

```{r}
dbGetQuery(con, "SELECT * from genelist limit 10")

```
















